# Generated by Django 4.2.1 on 2023-05-25 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_comments_listing_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="listing", name="endtime", field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="listing",
            name="high_bidder",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
