# Generated by Django 4.2.1 on 2023-05-25 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_listing_active_alter_listing_endtime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="high_bidder",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
