# Generated by Django 4.2.1 on 2023-05-26 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_rename_high_bidder_listing_bidders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="bidders",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.bid",
            ),
        ),
    ]
