# Generated by Django 4.2.1 on 2024-01-12 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_rename_name_listing_title_remove_listing_buyer_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="watchers",),
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="usersWatching",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
