# Generated by Django 4.2.1 on 2024-01-14 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_alter_comments_listing_alter_comments_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments", old_name="comment", new_name="message",
        ),
    ]
