# Generated by Django 4.2.1 on 2024-01-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_remove_bid_target_alter_bid_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="initialp",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
